### ISSUE TITLE
Apply policy levels on containers

### ISSUE THREAD

**Issue by vadorovsky** [rancher-sandbox/enclave#3]
Currently we apply the `baseline` policy to all containers. We need to come up with some mechanism to make BPF programs aware of which policies to apply for which containers.

# Goal

The perfect goal would be to:
* honor the Kubernetes labels:
  * `pod-security.kubernetes.io/enforce`
  * `pod-security.kubernetes.io/audit`
  * `pod-security.kubernetes.io/warn`
* provide some way for podman, docker, containerd etc. to apply the policy name
  * OCI wrapper?
  * OCI annotations/labels?

**Comment by mrostecki** [comment]
The tricky part of this issue will be getting k8s annotations. They are **not** passed by kubelet to runc. runc is aware of limited amount of information.
